

USE Asiakaspalvelu
GO

CREATE DATABASE Leipomo
GO

USE Leipomo
GO


CREATE TABLE Asiakas (
AsiakasID INTEGER NOT NULL PRIMARY KEY,
Nimi VARCHAR(128) NOT NULL,
Organisaatio BIT NOT NULL
)
GO

CREATE TABLE OrganisaatioAsiakas (
OrganiAsiaID INTEGER NOT NULL PRIMARY KEY,
AsiakasID INTEGER FOREIGN KEY REFERENCES Asiakas(AsiakasID),
Jalleenmyyja BIT NOT NULL
)
GO

CREATE TABLE Tuotteet (
TuoteID INTEGER NOT NULL PRIMARY KEY,
Tuotenimi VARCHAR(128) NOT NULL,
YksityisasiakasHinta INTEGER NOT NULL,
OrganisaatioHinta INTEGER NOT NULL
)
GO

CREATE TABLE Tilaukset (
TilausID INTEGER NOT NULL PRIMARY KEY,
TilausNumero INTEGER NOT NULL,
AsiakasID INTEGER FOREIGN KEY REFERENCES Asiakas(AsiakasID)
)
GO


CREATE TABLE TilauksenTuotteet (
TilausTuoteID INTEGER NOT NULL PRIMARY KEY,
TilausID INTEGER FOREIGN KEY REFERENCES Tilaukset(TilausID),
TuoteID INTEGER FOREIGN KEY REFERENCES Tuotteet(TuoteID)
)
GO